# This is a basic workflow to help you get started with Actions

name: fuzzertest CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install Dependeccies clang
        run: |
          sudo apt update
          sudo apt install clang llvm curl
      # Runs a set of commands using the runners shell
      - name: build and run program
        run: |
          ulimit -c unlimited
          mkdir build && cd build
          cmake .. && make
          sudo chmod -R +rwx /cores/*
          ./fuzzer_target_cov ../corpus/*
          llvm-profdata merge -sparse *.profraw -o default.profdata && llvm-cov show ./fuzzer_target_cov -instr-profile=default.profdata -name=LLVMFuzzerTestOneInput
          llvm-cov report ./fuzzer_target_cov -instr-profile=default.profdata > output.log
          curl www.google.com > index.html
          curl https://www.bing.com/search?q=linux+%E5%91%BD%E4%BB%A4%E8%A1%8C+post > search.html
          
      - name: if failure, list build file
        if: ${{ failure() }}
        run: |
          ls -al /cores
          ls -al build/coredump
          
      - name: save coredump
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with: 
          name: coredumpfile
          path: /cores
          
          
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: output-log-file
          path: |
            build/output.log
            build/*.html
            build/core*
